# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: projects/
    weight: 11
  - name: Publications
    url: /#talks
    weight: 12
  - name: Teaching
    url: /#news
    weight: 13
  - name: Outreach
    url: experience/
    weight: 20
  - name: Field
    url: 
    weight: 30
  - name: Codes
    url: 
    weight: 40
  - name: News
    url: /#news
    weight: 40
